version: '3.8'

services:
  app:
    build: ./python/
    container_name: application
    ports:
      - "8050:8050"
    depends_on:
      - database

  database:
    image: mysql:8
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: emc_lab_energy
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - app-data:/var/lib/mysql
    command: "--wait_timeout=28800 --interactive_timeout=28800 --max_connections=500"

volumes:
  app-data:
